export const EventsKey = {
  alertController: 'alertController',
  openBuyModal: 'openBuyModal',
  openBidModal: 'openBidModal',
  openSuccessBid: 'openSuccessBid',
  openSellModal: 'openSellModal',
  openLoginModal: 'openLoginModal',
  openPhotoModal: 'openPhotoModal',
  removeItem: 'removeItem',
  openCancel: 'openCancel',
  onSaveAsDraftModal: 'openSaveAsDraft',
  openDeleteModal: 'openDeleteModal',
  renewItem: 'renewItem',
  removeBid: 'removeBid',
  showOptions: 'showOptions',
  openbuyInfo: 'openbuyInfo',
  openbidInfo: 'openbidInfo',
  openSetExpire: 'openSetExpire',
  openGrade: 'openGrade',
  rejectBid: 'rejectBid',
  acceptBid: 'acceptBid',
  renewDetailedItem: 'renewDetailedItem',
  openReferralCode: 'openReferralCode',
  openSetBattery: 'openSetBattery',
  openExpiryModels: 'openExpiryModels',
  openDeleteItem: 'openDeleteItem'
};
