export const BREADCRUMBS = {
  ALL_ORDERS: 'All Orders',
  REPLACEMENT: 'Replacement',
  HOME: 'Home',
  ORDERS: 'Order Management',
  ORDERSV2: 'Order Management 2.0',
  UPFRONT_PAYMENTS: 'Consignments',
  ORDER_PAGE: 'Order Page',
  NEW_ORDERS: 'New Orders',
  NEW_UPFRONT: 'New',
  ACTIVE_ORDERS: 'Active Orders',
  APPROVED_UPFRONT: 'Approved',
  PAYOUT_TO_SELLER_UPFRONT: 'Payout to Seller',
  READY_TO_INSPECT: 'Ready to Inspect',
  CLOSED_ORDERS: 'Closed Orders',
  CLOSED_UPFRONT: 'Closed',
  REJECTED_UPFRONT: 'Rejected',
  RESERVATION_ORDERS: 'Reservation Orders',
  PAYOUTS: 'Payout Management',
  PAYOUTS2_0: 'Payout Management 2.0',
  BUYER_REFUND: 'Buyer Refund',
  SELLER_PAYOUT: 'Seller Payout',
  MESSAGE: 'Message',
  PROCESSING: 'Processing',
  SETTING: 'Settings',
  WALLET: 'Wallet',
  WALLET_MANAGEMENT: 'Wallets Management',
  WALLET_LIST: 'Wallets List',
  WITHDRAWAL: 'Withdrawal',
  USERS_APP: 'App Users',
  USERS: 'Users',
  WHATSAPP: 'Whatsapp',
  OMAUTOMATION: 'OM 2.0 Automations',
  COURIER_AUTOMATIONS: 'Courier Automations',
  ACTIVITY_LOG: 'Activity Log',
  ACCOUNT: 'Account',
  QUESTIONS: 'Questions',
  LOGISTICS: 'Logistics Management',
  LOGISTICS_VENDORS: 'Logistics Vendors',
  LOGISTICS_TIERS: 'Logistics Tiers',
  RULES_ENGINE: 'Rules Engine',
  BNPL_ORDERS: 'BNPL Orders Module',
  PAYMENT_LOGS: 'Payment Logs',
  CONFIRMED_ORDERS: 'Confirmed Orders',
  DELIVERY: 'Delivery',
  SHIPPING: 'Shipping',
  DISPUTE: 'Dispute',
  BACKLOG: 'Backlog Management',
  RESERVATION: 'Reservation',
  FLAGGED_LISTINGS: 'Flagged Listings',
  UNCHECKED: 'Unchecked',
  RECENT: 'Most Recent',
  POSITIVE: 'Positive Flagged (AI)',
  DISCOUNT: 'Highest Discount %',
  LISTING: 'Listing Details',
  UNFILTERED: 'Un-Filtered',
  STORIES: 'Stories',
  CAR_REAL_STATE: 'Cars and Real State',
  SUPER_CATEGORIES: 'Super Categories',
  CATEGORIES: 'Categories',
  BRANDS: 'Brands',
  MODELS: 'Models',
  ADDONS: 'Addons',
  PROMOCODE: 'Promocode',
  PROMOCODE_LIST: 'List',
  VARIANTS: 'Variants',
  CONDITIONS: 'Conditions',
  ONHOLD: 'OnHold',
  CONSIGNMENT: 'Consignment',
};
