kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: true
metadata:
  name: {{ include "chart.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- if .Values.general.labels }}
  labels:
    {{- toYaml .Values.general.labels | nindent 4 }}
  {{- end }}
  