import { GetBanners } from './banner';
import {
  ValidIdsForPromoCode,
  GetProductDetailsForPromoCodeValidation,
  ValidateUserUsageOfPromoCode,
} from './commissionGrpc';
import { GetFeeds } from './feed';
import { GetInvoiceGenerationFlag } from './invoice';
import {
  CancelOrder,
  CreateDmOrder,
  CreateOrder,
  CreateSmsaTracking,
  FetchInvoiceGenerationData,
  GenerateSmsaTracking,
  GetCompletionRateUser,
  GetOrderDetail,
  GetOrderDetailById,
  GetOrderDetailByUserType,
  GetOrderSaleAnalytics,
  GetPenalizedOrders,
  GetPendingPayoutAnalytics,
  GetPendingPayoutPagination,
  GetTopSellingProductModels,
  GetUserProfile,
  UpdateDmOrder,
  UpdateLogisticService,
  UpdatePaymentStatusOfOrder,
  UpdateOrderAttribute,
  ProcessReserveFinancingPayment,
  GetUserLastOrderData,
  SubmitRating,
  GetCategoryModelsCount,
} from './order';
import { GetListingFees, UpdateSecurityFee } from './paymentGrpc';
import {
  GetBidSummary,
  GetCountdownValInHours,
  GetProductStatuses,
  GetProducts,
  GetProductsForProductService,
  GetRecentlySoldProducts,
  GetViewedProducts,
  UpdateHighestBid,
  UpdateProduct,
  ValidateSellerDetectionNudge,
  getPromoCode,
} from './product';
import {
  CheckUserOTP,
  CreateNewUser,
  GetDmUser,
  GetDmUsers,
  GetLegacyUserViaLocalPhone,
  GetPermissions,
  GetSellerBadge,
  GetUser,
  GetUsers,
  GetUsersByPhone,
  SetUserOTP,
  UpdateInactiveUser,
  UpdatePenaltyFlag,
} from './user';
import { GetMarketPriceByVariantId, GetVariants } from './variant';

export default {
  GetUser,
  GetUsers,
  GetOrderDetail,
  GetPermissions,
  GetDmUser,
  GetDmUsers,
  GetUsersByPhone,
  GetMarketPriceByVariantId,
  UpdateHighestBid,
  GetProducts,
  GetProductStatuses,
  GetViewedProducts,
  GetRecentlySoldProducts,
  CreateOrder,
  UpdateLogisticService,
  GetBidSummary,
  GetVariants,
  GetFeeds,
  GetBanners,
  GetLegacyUserViaLocalPhone,
  CreateNewUser,
  UpdateInactiveUser,
  CancelOrder,
  UpdatePenaltyFlag,
  GetInvoiceGenerationFlag,
  UpdatePaymentStatusOfOrder,
  GetCountdownValInHours,
  ValidateSellerDetectionNudge,
  GetProductsForProductService,
  getPromoCode,
  GetSellerBadge,
  FetchInvoiceGenerationData,
  GetOrderSaleAnalytics,
  GetPendingPayoutAnalytics,
  GetPendingPayoutPagination,
  GetPenalizedOrders,
  GetCompletionRateUser,
  GetTopSellingProductModels,
  SetUserOTP,
  CheckUserOTP,
  CreateSmsaTracking,
  UpdateOrderAttribute,
  UpdateProduct,
  GetListingFees,
  UpdateSecurityFee,
  ValidIdsForPromoCode,
  GetProductDetailsForPromoCodeValidation,
  ValidateUserUsageOfPromoCode,
  ProcessReserveFinancingPayment,
  GenerateSmsaTracking,
  GetOrderDetailById,
  GetOrderDetailByUserType,
  CreateDmOrder,
  UpdateDmOrder,
  GetUserProfile,
  GetUserLastOrderData,
  SubmitRating,
  GetCategoryModelsCount,
};
