kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{project-name}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{project-name}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%  
  template:
    metadata:
      labels:
        app: {{project-name}}
    spec:
      containers:
        - name: {{project-name}}
          image: {{CI_REGISTRY_IMAGE}}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: '{{environment}}'
            - name: PORT
              value: '3000'
            - name: MONGODB_URI
              value: '{{mongodb_uri}}'
          ports:
            - containerPort: 3000
      imagePullSecrets: 
        - name: registry-credentials
      restartPolicy: Always


---


kind: Service
apiVersion: v1
metadata:
  name: {{project-name}}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{project-name}}
