apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{project-name}}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - admin.qa.soum.sa
    secretName: {{project-name}}-tls
  rules:
  - host: admin.qa.soum.sa
    http:
      paths:
      - backend:
          serviceName: {{project-name}}
          servicePort: 80