apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{KUBE_NAMESPACE}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiLWRlcGxveS10b2tlbiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6IlJkTnlwNnhGMUpXNTVpZHhGRnREIiwKICAgICAgICAgICAgImVtYWlsIjoiYWlrMTQxM0BnbWFpbC5jb20iLAogICAgICAgICAgICAiYXV0aCI6IloybDBiR0ZpTFdSbGNHeHZlUzEwYjJ0bGJqcFNaRTU1Y0RaNFJqRktWelUxYVdSNFJrWjBSQT09IgogICAgCX0KICAgIH0KfQo=
