export enum DmActionsEnum {
  CONFIRM_AVAILABILITY = 'Confirm Availability',
  CONFIRMED_AVAILABILITY = 'Confirmed Availability',
  CONFIRM_UNAVAILABILITY = 'Confirm Unavailability',
  CONFIRMED_UNAVAILABILITY = 'Confirmed Unavailability',
  BUYER_WITHDRAW = 'Buyer Withdraw',
  ASSIGN_LOGISTICS_SERVICE = 'Assign Logistics Service',
  AWAIT_SHIPPING = 'Await Shipping',
  AWAIT_PICKUP = 'Await Pickup',
  REQUEST_REFUND = 'Request Refund',
  INVALID_DISPUTE = 'Invalid Dispute',
  VALID_DISPUTE = 'Valid Dispute',
  CANCEL_DISPUTE = 'Cancel Dispute',
  RETURN_IN_TRANSIT = 'Return Intransit',
  RESOLVED_WITHOUT_RETURN = 'Resolved without return',
  REQUEST_PAYOUT = 'Request Payout',
  RETURNED = 'Returned',
  CONFIRM_DROPOFF = 'Confirm Dropoff',
  BACKLOG_SHIPPING = 'Backlog Shipping',
  CONVERT_TO_PICKUP = 'Convert to Pickup',
  CONFIRM_PICKUP = 'Confirm Pickup',
  BACKLOG_PICKUP = 'Backlog Pickup',
  CONVERT_TO_DROPOFF = 'Convert to Dropoff',
  DELIVERED = 'Delivered',
  CONFIRM_DELIVERY = 'Confirm Delivery',
  REFUND_HOLD = 'Refund Hold',
}

export enum DmDeliveryActionsEnum {
  DELIVERED = 'Delivered',
  BACKLOG_INTRANSIT = 'Backlog intransit',
  LOST_SHIPMENT = 'Lost Shipment',
  REQUEST_PAYOUT = 'Request Payout',
  DISPUTE_RAISE = 'Dispute Raised',
  SOUM_DELIVERED = 'SOUM Delivered',
}
