import { LeanDocument } from 'mongoose';
import { SettingDocument } from '../../../src/models/Setting';

export const mockSettings = [
  {
    _id: '61e91e6c260801002df1eac6',
    value: false,
    status: 'Enabled',
    name: 'skip_defect_photos',
    description: 'skip_defect_photos',
    setting_category: 'Global',
    type: 'boolean',
  },
  {
    _id: '61e91e6c260801002df1eac7',
    value: true,
    status: 'Enabled',
    name: 'product_approval',
    description: 'product_approval',
    setting_category: 'Global',
    type: 'boolean',
  },
  {
    _id: '61e91e6c260801002df1eac8',
    value: '01B9FF',
    status: 'Enabled',
    name: 'theme_color',
    description: 'theme_color',
    setting_category: 'Global',
    type: 'string',
  },
  {
    _id: '61e91e6c260801002df1eac9',
    value: 5,
    status: 'Enabled',
    name: 'buyer_commission_percentage',
    description: 'buyer_commission_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eaca',
    value: 5,
    status: 'Enabled',
    name: 'seller_commission_percentage',
    description: 'seller_commission_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eacb',
    value: 0,
    status: 'Enabled',
    name: 'shipping_charge_percentage',
    description: 'shipping_charge_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eacc',
    value: 15,
    status: 'Enabled',
    name: 'vat_percentage',
    description: 'vat_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eacd',
    value: 0.1,
    status: 'Enabled',
    name: 'bidding_amount',
    description: 'bidding_amount',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eace',
    value: 80,
    status: 'Enabled',
    name: 'start_bid_percentage',
    description: 'start_bid_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1eacf',
    value: 200,
    status: 'Enabled',
    name: 'referral_credit_amount',
    description: 'referral_credit_amount',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1ead0',
    value: 'Seller',
    status: 'Enabled',
    name: 'referral_credit_type',
    description: 'referral_credit_type',
    setting_category: 'Global',
    type: 'string',
  },
  {
    _id: '61e91e6c260801002df1ead1',
    value: 'Percentage',
    status: 'Enabled',
    name: 'referral_discount_type',
    description: 'referral_discount_type',
    setting_category: 'Global',
    type: 'string',
  },
  {
    _id: '61e91e6c260801002df1ead2',
    value: 200,
    status: 'Enabled',
    name: 'referral_fixed_amount',
    description: 'referral_fixed_amount',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61e91e6c260801002df1ead3',
    value: 10,
    status: 'Enabled',
    name: 'referral_percentage',
    description: 'referral_percentage',
    setting_category: 'Global',
    type: 'number',
  },
  {
    _id: '61fb96961bc5af002c946823',
    value: 'sellPrice',
    status: 'Enabled',
    name: 'model_order_type',
    description: 'model_order_type',
    type: 'option',
    setting_category: 'Global',
  },
  {
    _id: '62011921525564002cb69ce2',
    value: 'App,Web',
    status: 'Enabled',
    name: 'MADA',
    description: 'MADA',
    type: 'option',
    setting_category: 'Global',
  },
  {
    _id: '6201193de0efc6002d70a5c7',
    value: 'App,Web',
    status: 'Enabled',
    name: 'VISA_MASTER',
    description: 'VISA_MASTER',
    type: 'option',
    setting_category: 'Global',
  },
  {
    _id: '6201197c1bc5af002c9468d9',
    value: 'Web,App',
    status: 'Enabled',
    name: 'APPLEPAY',
    description: 'APPLEPAY',
    type: 'option',
    setting_category: 'Global',
  },
  {
    _id: '62011f31363133002c20e527',
    value: '',
    status: 'Enabled',
    name: 'Tabby',
    description: 'Tabby',
    type: 'option',
    setting_category: 'Global',
  },
  {
    _id: '621b5fa8f628ef002c7aeb5b',
    value: 'Web,App',
    status: 'Enabled',
    name: 'STC_PAY',
    description: 'STC_PAY',
    type: 'option',
    setting_category: 'Global',
  },
] as LeanDocument<SettingDocument>[];
