kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{project-name}}
spec:
  replicas: 8
  selector:
    matchLabels:
      app: {{project-name}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%  
  template:
    metadata:
      labels:
        app: {{project-name}}
    spec:
      containers:
        - name: {{project-name}}
          image: {{CI_REGISTRY_IMAGE}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets: 
        - name: registry-credentials
      restartPolicy: Always


---


kind: Service
apiVersion: v1
metadata:
  name: {{project-name}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{project-name}}
